name 'swarm'
maintainer 'Brent Walker'
maintainer_email 'brent@moveablecube.com'
license 'apache2'
description 'Installs/Configures Docker Swarm'
long_description 'Configures nodes to run Docker Swarm'
issues_url 'https://github.com/tacchino/swarm/issues'
source_url 'https://github.com/tacchino/swarm'
version '0.1.2'

depends 'docker', '~> 2.6'
